### ISSUE TITLE
UserAccount validation of m2m relationship doesnt work on initial save

### ISSUE THREAD

**Issue by tsujamin** [tsujamin/digi-approval#1]
The UserAccount model has a many-to-many relationship between Users and Organisations (for the purpose of users performing workflows on behalf of organistions). 

Currently the save method of this model validates that a user has no sub-accounts and that its parent accounts are all Organisations (reverse validations for organisation accounts). It was observed that no exception is raised when this rule is broken during UserAccount creation (via django-admin page). If the UserAccount is re-saved the exception is thrown.

This is a safety validation so while it is optimal for it to work, it isnt super critical.

**Comment by ajdlinux** [comment]
Have we fixed this?

**Comment by tsujamin** [comment]
We probably didn't fix this
